baseURL = 'https://justinhhorner.com'
languageCode = 'en-us'
theme = "hugo-poison"
paginate = 10
pluralizeListTitles = false

[params]
brand = "Justin Horner"
dark_mode = true
description = "Senior Software Engineer at Meta, Supernatural"
remote_brand_image = "https://avatars.githubusercontent.com/u/175179517?v=4"
og_image = "win_bypass"
# brand_image = "/images/avatar.png"

# Menu
# Name:         The name to display on the menu.
# URL:          The directory relative to the content directory.
# HasChildren:  If the directory's files should be listed.  Default is true.
# Limit:        If the files should be listed, how many should be shown.
menu = [
    { Name = "About", URL = "/about/", HasChildren = false },
    { Name = "Blog", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
]

# Social
twitter_url = "https://www.twitter.com/justinhhorner"
github_url = "https://github.com/justin-horner"
linkedin_url = "https://www.linkedin.com/in/justinhhorner/"
email_url = "mailto://contact@justinhhorner.com"

# RSS
rss_icon = true
rss_section = "blog"

# Sidebar Colors
moon_sun_background_color = "#515151" # default is #515151
moon_sun_color = "#FFF"               # default is #FFF
sidebar_a_color = "#FFF"              # default is #FFF
sidebar_bg_color = "#202020"          # default is #202020
sidebar_h1_color = "#FFF"             # default is #FFF
sidebar_img_border_color = "#515151"  # default is #515151
sidebar_p_color = "#909090"           # default is #909090
sidebar_socials_color = "#FFF"        # default is #FFF

# Content (Light) Colors
code_color = "#000"                     # default is #000
code_background_color = "#E5E5E5"       # default is #E5E5E5
code_block_color = "#FFF"               # default is #FFF
code_block_background_color = "#272822" # default is #272822
content_bg_color = "#FAF9F6"            # default is #FAF9F6
date_color = "#515151"                  # default is #515151
link_color = "#268BD2"                  # default is #268BD2
list_color = "#5A5A5A"                  # default is #5A5A5A
post_title_color = "#303030"            # default is #303030
table_border_color = "#E5E5E5"          # default is #E5E5E5
table_stripe_color = "#F9F9F9"          # default is #F9F9F9
text_color = "#222"                     # default is #222

# Content (Dark) Colors
code_color_dark = "#FFF"                     # default is #FFF
code_background_color_dark = "#515151"       # default is #515151
code_block_color_dark = "#FFF"               # default is #FFF
code_block_background_color_dark = "#272822" # default is #272822
content_bg_color_dark = "#121212"            # default is #121212
date_color_dark = "#9A9A9A"                  # default is #9A9A9A
link_color_dark = "#268BD2"                  # default is #268BD2
list_color_dark = "#9D9D9D"                  # default is #9D9D9D
post_title_color_dark = "#DBE2E9"            # default is #DBE2E9
table_border_color_dark = "#515151"          # default is #515151
table_stripe_color_dark = "#202020"          # default is #202020
text_color_dark = "#EEE"


[taxonomies]
category = "categories"
tag = "tags"
