baseURL = 'https://justinhhorner.com'
languageCode = 'en-us'
title = 'Justin Horner'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
description = "Senior Software Engineer at Meta, Supernatural"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome, nerds'
homeIntroContent = """
I develop games, game engines and related tools + services. I'm a Senior Software Engineer currently working on [Supernatural](https://getsupernatural.com) at [Meta](https://meta.com)
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 50
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "twitter"
url = "https://www.x.com/justinhhorner/"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/justinhhorner/"
[[params.social]]
name = "twitch"
url = "https://twitch.tv/justinhhorner"
[[params.social]]
name = "github"
url = "https://github.com/justin-horner"
[[params.social]]
name = "email"
url = "mailto:contact@justinhhorner.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"
[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
